# Generated by Django 3.1.4 on 2020-12-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_speed', models.FloatField()),
                ('download_error', models.CharField(max_length=200)),
                ('upload_speed', models.FloatField()),
                ('upload_error', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
