# Generated by Django 3.1.4 on 2020-12-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='download_error',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='upload_error',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
